# Dockerfile
FROM nginx:alpine

# cd EcoGeste/FlutterWeb
# docker build -t flutter/web/ecogeste .
# docker run --rm -d -p 6834:80 flutter/web/ecogeste

# docker run -d -p 8080:80 my-static-webapp

# Remove default nginx static files
RUN rm -rf /usr/share/nginx/html/*

# Copy static files to nginx directory
COPY ./ /usr/share/nginx/html

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]