# docker compose -f "compose/docker-compose-mssql.yml" up -d --build


name: stagiares_sqlserver
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: stagiares_sqlserver
    ports:
      - "8793:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: sa_pass2025.11
      MSSQL_PID: Express
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data:

